services:
  app:
    build:
      context: .
    restart: unless-stopped
    ports:
      - '${DOCKER_NGINX_PORT-4000}:2000'
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - frontend

networks:
  frontend:
    driver: bridge